version: "3.9"

services:
  mongodb:
    image: mongo:6.0
    container_name: catalog-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: catalog_service_dev
    volumes:
      - mongodb_data:/data/db
    networks:
      - catalog-network

  catalog-service:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: catalog-service
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DATABASE: catalog_service_dev
      SERVER_PORT: 8080
    depends_on:
      - mongodb
    networks:
      - catalog-network

volumes:
  mongodb_data:
    driver: local

networks:
  catalog-network:
    driver: bridge